### ISSUE TITLE
inference my own dataset

### ISSUE THREAD

**Issue by stanny880913** [nesl/radar-camera-fusion-depth#4]
Hello, I want to inference my own dataset, my data is only a pair of jpg and pcd file!! and some parameter for camera and radar calibration, is it possible to generate it!!??
Thank you

**Comment by thecyclone** [comment]
Hi @stanny880913,
In order to use our method on your own dataset, you would need the following:

1. Transformation matrix -> to project radar points into the camera's frame of reference.
2. Source of ground truth -> in our case, we have lidar point cloud that serves as the source of ground truth. If you do not have lidar points, you can get the ground truth using consecutive camera images.
3. Some way to find out the movement between consecutive frames (we densify our point clouds by forward and back projections) -> nuScenes has IMU but you can use consecutive camera images for this as well although your mileage may vary.

Once you have these, you should be able to use our method on your data. You would need to go through our code and modify the relevant sections.
